### ISSUE TITLE
Odroid C2 Ubuntu (release 27/09/2017) OSD_GET_DMA_BUF_FD failed. (-1)

### ISSUE THREAD

**Issue by LinhDNguyen** [OtherCrashOverride/CXVideoCube#1]
Hello @OtherCrashOverride ,

Thank you for the code. I'm trying to make it works on X11 (actually, fbdev got EGL_BAD_ALLOC when create surface as well). And I facing with error when get DMA buf for /dev/fb0 at https://github.com/nvl1109/CXVideoCube/blob/master/main.cpp#L623. 
Here are output log:
```
odroid@odroid64:~/p/code/CXVideoCube⟫ sudo ./videocube
EGL: major=1, minor=4
EGL: Vendor=ARM
EGL: Version=1.4 Linux-r6p1-01rel0
EGL: ClientAPIs=OpenGL_ES
EGL: Extensions=EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync EGL_KHR_fence_sync EGL_KHR_swap_buffers_with_damage EGL_EXT_swap_buffers_with_damage EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_KHR_create_context EGL_KHR_partial_update EGL_KHR_create_context_no_error
EGL: ClientExtensions=EGL_EXT_client_extensions EGL_EXT_platform_base EGL_KHR_platform_x11

red colorSize: 8
green colorSize: 8
blue colorSize: 8
alpha colorSize: 8
depth size: 24
stencil size: 8
sample size: 0
file handle: a
screen info: width=3840, height=2160, bpp=32
OSD_GET_DMA_BUF_FD failed. (-1): Operation not permitted

```

Could you please take alook and give me your suggestions? Thank you.

**Comment by LinhDNguyen** [comment]
I think it is because of the meson-fb driver does not support ``OSD_GET_DMA_BUF_FD`` in its ``ioctl()``.

So, where can I get supported driver? Thank you.

**Comment by LinhDNguyen** [comment]
Hello,

I have found your patch for DMA_BUF (https://github.com/OtherCrashOverride/linux-hardkernel/commit/5675ee625004a9b4bd92dfd58019f4be354ff702).

Now I have problem to enable vfm_grabber driver.
I have built the driver, probe it successfully. But I think it needs to update the DTS file to enable vfm_grabber? Thank you.

**Comment by LinhDNguyen** [comment]
And I think I also need the mali driver which supports EGL_EXT_image_dma_buf_import. Could you please share me the link of the suitable mali driver? Thank you.

**Comment by OtherCrashOverride** [comment]
I do not have any links for Mali drivers.  You can inquire on the Odroid forum about it.

**Comment by LinhDNguyen** [comment]
Thank you. I will ask in Odroid forum.
